### ISSUE TITLE
Disappear on scroll

### ISSUE THREAD

**Issue by Smiller193** [rechsteiner/Parchment#235] opened 2018-08-22 02:37 UTC
Is there any way to make the paging menu disappear on the scroll. Most of my paging view controllers are collectionviews and I don't like how the content disappears under the menu when I scroll vertically.  Is it possible to do this?

**Comment by Smiller193** [comment] 2018-08-22 21:17
@rechsteiner im confused on how this was done

**Comment by rechsteiner** [comment] 2018-08-23 07:14
Hi! I've created a new example target called `ScrollExample` that you can check out for implementation details. It's done by overriding the menu constraints and updating the top constraint whenever the currently selected scroll view is scrolling.

Here's the implementation: https://github.com/rechsteiner/Parchment/blob/master/ScrollExample/ViewController.swift

Let me know if that works for you 🙂

**Comment by Smiller193** [comment] 2018-08-23 18:07
thanks I will be trying now

**Comment by Smiller193** [comment] 2018-08-23 18:41
how would I switch it so that I can use paging items instead of paging index items because I am trying to follow the unsplash example for the menu

**Comment by Smiller193** [comment] 2018-08-23 18:44
because I am getting a casting error that says this 

> Could not cast value of type 'UIPractice.ImageItem' (0x10ebaa918) to 'Parchment.PagingIndexItem' (0x10f053158).

where ImageItem is a paging item

**Comment by rechsteiner** [comment] 2018-08-23 18:51
You need to specify the paging type when defining the PagingViewController. E.g:

```
class CustomPagingViewController: PagingViewController<ImageItem> {
```

**Comment by Smiller193** [comment] 2018-08-23 18:58
I followed your example and when i scrolled up nothing moved? it still went under it. Would it matter if it was a collectionview ?

**Comment by rechsteiner** [comment] 2018-08-23 19:01
No, that shouldn't matter. Just change `UITableViewDelegate` to `UICollectionViewDelegate` like this:

```Swift
extension ViewController: UICollectionViewDelegate {
  
  func scrollViewDidScroll(_ scrollView: UIScrollView) {
    // Offset the menu view based on the content offset of the
    // scroll view.
    if let menuView = pagingViewController.view as? CustomPagingView {
      menuView.menuTopConstraint?.constant = -menuOffset(for: scrollView)
    }
  }
  
}
```

Maybe try adding a breakpoint to see if that method gets called at all? You need to remember to set the `delegate` on your collection view.

**Comment by Smiller193** [comment] 2018-08-23 19:04
yeah that method doesn't get called at all and I am definitely setting the delegate as can be seen in this code block


  func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, viewControllerForIndex index: Int) -> UIViewController {
        let menu = MenuFeedController()
        let menuHeight = pagingViewController.options.menuHeight
        let insets = UIEdgeInsets(top: menuHeight, left: 0, bottom: 0, right: 0)
        menu.collectionView.contentInset = insets
        menu.collectionView.scrollIndicatorInsets = insets
        menu.collectionView.delegate = self
        menu.rootRef = self
        return menu
    }


Would it make a difference if I am also setting the delegate in the actual file that contains the collectionView or the actual collectionViewController because I am setting the delegate there as well

**Comment by Smiller193** [comment] 2018-08-23 19:05
Like so 


lazy var collectionView: UICollectionView = {
    let layout =   UICollectionViewFlowLayout()
    layout.minimumLineSpacing = 0
    layout.minimumInteritemSpacing = 0
    layout.scrollDirection = .vertical
    let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
    collectionView.backgroundColor = .clear
    return collectionView
}()

@objc func setupViews(){
    collectionView.delegate = self
    collectionView.dataSource = self
    view.addSubview(collectionView)
    collectionView.snp.makeConstraints { (make) in
        make.edges.equalTo(view.safeAreaLayoutGuide)
    }
}

**Comment by rechsteiner** [comment] 2018-08-23 19:08
Yeah, that's the problem. You can only have one delegate at the time. I would just create a separate delegate on the view controller you are displaying. E.g:

```Swift
protocol ContentViewControllerDelegate: class {
  func contentViewControllerDidScroll(_: ContentViewController)
}
```

Then call that delegate in your `UICollectionViewDelegate`:

```
func scrollViewDidScroll(_ scrollView: UIScrollView) {
    delegate?.contentViewControllerDidScroll(self)
}
```

**Comment by Smiller193** [comment] 2018-08-23 19:13
So just to make sure. I have two files the view controller that sets up the paging menu and the various collectionViewControllers I understand the protocol usage but when you say then call that delegate in your UICollectionViewDelegate am i calling it in the file that sets up the paging view controller or the view controller that contains the actual collectionView

**Comment by rechsteiner** [comment] 2018-08-23 19:16
In the view controller that contains the actual collection view 🙂

**Comment by Smiller193** [comment] 2018-08-23 19:41
Okay last question


extension MainViewController: UICollectionViewDelegate {
    
    
[    func contentViewControllerDidScroll(_: MenuFeedController) {
        if let menuView = pagingViewController.view as? CustomPagingView {
            menuView.menuTopConstraint?.constant = -menuOffset(for: )
        }
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        // Offset the menu view based on the content offset of the
        // scroll view.
        if let menuView = pagingViewController.view as? CustomPagingView {
            menuView.menuTopConstraint?.constant = -menuOffset(for: scrollView)
        }
    }
}](url)


What would i put in the new function when the delegate gets called i should be passing the contentViewController as a parameter which would let me access the scrollView correct?

**Comment by Smiller193** [comment] 2018-08-23 19:46
I think i got it like this ?


    func contentViewControllerDidScroll(menuFeed : MenuFeedController) {
        if let menuView = pagingViewController.view as? CustomPagingView {
            menuView.menuTopConstraint?.constant = -menuOffset(for: menuFeed.collectionView)
        }
    }

**Comment by rechsteiner** [comment] 2018-08-23 19:46
Yeah, that should work

**Comment by Smiller193** [comment] 2018-08-23 19:51
cool got it thanks bro

**Comment by Smiller193** [comment] 2018-08-24 10:09
is there a way to incorporate what you did hear into what you taught me or would it be just as easy as taking the parts that make the menu height change?

**Comment by Smiller193** [comment] 2018-08-24 10:12
https://github.com/rechsteiner/Parchment/blob/master/UnplashExample/ViewController.swift

**Comment by rechsteiner** [comment] 2018-08-24 12:04
Yeah, you can modify the menu height/top constraint to whatever you like. You can just copy over the `menuHeight` calculation from the example if you want the same behaviour in your app.

**Comment by Smiller193** [comment] 2018-08-24 12:26
Yeah im playing with it now currently my menu item shrinks a little too much 

<img width="370" alt="screen shot 2018-08-24 at 8 26 16 am" src="https://user-images.githubusercontent.com/16108750/44584585-74f59b00-a777-11e8-9d4c-8df5aa6ad910.png">

**Comment by Smiller193** [comment] 2018-08-24 12:27
we have to change the maxChange property to control that correct

**Comment by Smiller193** [comment] 2018-08-24 12:31
thanks for everything bro

**Comment by rechsteiner** [comment] 2018-08-24 13:12
Hmm, the should be selectable when it's collapsed as well. Seems to work just fine in the Unsplash example.

**Comment by rechsteiner** [comment] 2018-08-26 13:29
Did you manage to get the selection working?

**Comment by Smiller193** [comment] 2018-08-27 02:26
no i didn't

**Comment by rechsteiner** [comment] 2019-02-24 14:45
@Smiller193 I'm not sure I understand exactly what the problem is. I'm closing this issue for now since it's not really related to scrolling. Can you open a separate issue related the selection if this is still an issue? 🙂

**Closed by rechsteiner** 2019-02-24 14:45 UTC
