### ISSUE TITLE
Weird scrolling bug

### ISSUE THREAD

**Issue by peter-szucs** [rechsteiner/Parchment#563] opened 2021-03-17 09:32 UTC
Hi!
First of all thanks for a great library!

We recently decided to try and incorporate this into our app since it would suit our needs perfectly. 
We also added a collapsing header effect with it.
So we first made a test project to test it out and just as we had refactored it into our own app we noticed a very strange bug that we just can't seem to pinpoint the problem with.
At first we thought maybe its something in our own app but i opened up the test project and its there as well.

This GIF will show you the issue. Its even worse when we only have one tab/screen. It then even gets hard to scroll down for a refresh properly without triggering this issue.

![parchmentBug](https://user-images.githubusercontent.com/55179291/111443581-cedd5800-8709-11eb-840b-8cabebaea1bf.gif)

Do you have any idea as of why and where this might be happening ?

Sample code for implementation:

```
private var pagingViewController = PagingViewController()

pagingViewController.dataSource = self
pagingViewController.register(PagingCustomCell.self, for: CustomPagingItem.self)
addChild(pagingViewController)
pagingViewController.borderOptions = .hidden
pagingViewController.menuItemSize = .selfSizing(estimatedWidth: 100, height: 40)
pagingViewController.indicatorClass = CustomIndicatorView.self
pagingViewController.indicatorOptions = .visible(
    height: 32,
    zIndex: -1,
    spacing: .zero,
    insets: UIEdgeInsets(top: 0, left: 0, bottom: 5, right: 0)
)
pagingViewController.indicatorColor = .purple
pagingViewController.collectionView.contentInset = UIEdgeInsets(top: 0, left: 16, bottom: 0, right: 16)

view.addSubview(pagingViewController.view)
pagingViewController.backgroundColor = .clear
pagingViewController.didMove(toParent: self)
pagingViewController.view.translatesAutoresizingMaskIntoConstraints = false
pagingViewController.view.snp.makeConstraints { (m) in
    m.top.equalTo(headerView.snp.bottom)
    m.left.right.bottom.equalToSuperview()
}

// Put shadow beneath tabs for collapsing header
pagingViewController.collectionView.layer.masksToBounds = true
pagingViewController.collectionView.layer.shadowOffset = CGSize(width: 0, height: 1)
pagingViewController.collectionView.layer.shadowRadius = 1
pagingViewController.collectionView.layer.shadowOpacity = 0.3

extension ViewController: PagingViewControllerDataSource {
    
    func numberOfViewControllers(in pagingViewController: PagingViewController) -> Int {
        return pages.count
    }
    
    func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
        let currentVc = pages[index]
        
        if let currentVc = currentVc {
            return currentVc
        } else {
            let tableViewVC = TableViewController()
            tableViewVC.innerTableViewScrollDelegate = self
            
            pages[index] = tableViewVC
            
            return tableViewVC
        }
    }
    
    func pagingViewController(_: PagingViewController, pagingItemAt index: Int) -> PagingItem {
        return CustomPagingItem(index: index, text: "View \(index+1)")
    }
}
```

**Comment by ageevvalentin** [comment] 2021-03-19 09:27
This is not reproduced in version 2.4.0

**Comment by peter-szucs** [comment] 2021-03-19 12:57
Thanks for telling us this. We'll use this version until its fixed hopefully in v. 3.

**Comment by rechsteiner** [comment] 2021-04-05 10:53
Hi @peter-szucs! Which version are you using? There was a fix for this in 3.0.1. I tried implementing you example locally, with a header view on the top and using SnapKit in the same way, and it seems to work fine here.

**Comment by peter-szucs** [comment] 2021-04-06 08:00
Hello @rechsteiner ! Thanks for your reply,
We are using 3.0.1 when getting the bug.
After downgrading to 2.4.0 the bug did dissapear though.
Let me know if you want some more code or something to look at that could help troubleshoot the issue.

**Comment by rechsteiner** [comment] 2021-04-06 08:20
Okay, thanks. Are you able to reproduce it in one of the example projects? That would be very helpful

**Comment by peter-szucs** [comment] 2021-04-07 12:50
We didn't try out the example projects, and now that i've cloned it down could you tell me how to actually run it ? I can't really figure out how, it builds and thats it.
I'm still very much a beginner in iOS development. :)

**Comment by mishaPetrus** [comment] 2021-04-08 13:20
Hello @rechsteiner.
First of all thanks for a perfect library!

In general, I have the same problem with scrolling. I found the place in the library, where it can be fixed. As you can see on the screenshot **scrollView.contentOffset** has vertical and horizontal offset. If you uncomment the code, horizontal scrolling will work well. 

![Screenshot 2021-04-08 at 16 04 58](https://user-images.githubusercontent.com/22256384/114033666-1f1d8500-9886-11eb-9354-c4f354a7fcee.png)

**Comment by rechsteiner** [comment] 2021-04-08 14:52
Thanks! Are you able to reproduce the bug in one of the examples? I haven't been able to reproduce it myself, so I can't verify that the changes are actually fixing it

**Comment by mishaPetrus** [comment] 2021-04-08 16:01
A very strange thing, because I can't reproduce this with an Example project. I'm probably setting something wrong.

**Comment by rechsteiner** [comment] 2021-04-08 16:38
I’m quite sure it's a problem with Parchment, because it wasn’t an issue in v2.4. I just need to reproduce it to fix it

**Comment by minaMagedNaeem** [comment] 2021-05-30 10:36
I tried @mishaPetrus fix and it worked just fine, @rechsteiner please fix this issue ASAP or accept the answer and update the pod.

**Comment by rechsteiner** [comment] 2021-05-30 10:51
@mishaPetrus I need to be able to reproduce it in order to provide a reliable fix. If you have any details on how to reproduce it that would be great. Even better if you are able to reproduce it in one of the example projects

**Comment by BaoDotMark** [comment] 2021-07-29 03:07
I got this exact scrolling issue. I have 5 menus: 1st(20 items) - 2nd(20 items) - 3rd(10 items) - 4th(20 items) - 5th(10 items). When I scroll from 20 items menu to 10 items menu, this bug happens. It's normal from 1st menu to 2nd menu.

**Comment by toptomsk** [comment] 2021-08-31 01:32
I got this issue too, and misha's answer work great for me.

**Comment by toptomsk** [comment] 2021-11-05 03:20
@rechsteiner Hi Martin! 
I have messaged example to your twitter, hope u check it and can find out this bug.

**Closed** 2022-01-15 13:58 UTC

**Comment by sugitatestblue** [comment] 2022-01-19 03:14
@ageevvalentin
Thank you fix it.
However, the fix version didn't release yet.
I wanted the hash of https://github.com/rechsteiner/Parchment/commit/c8ec776237abe1349f4646ca79862a9c72a8aaa0
but, I couldn't set the hash version on Swift Packaging Manger.
I should use 2.4.0 version.
