### ISSUE TITLE
dyld: Symbol not found? after update to v 2.3

### ISSUE THREAD

**Issue by YanwuX** [rechsteiner/Parchment#474] opened 2020-04-08 20:28 UTC
I updated pods and when I run the project in devices, error message pops up.

target platform ios 12, Xcode 11.4

dyld: Symbol not found: _$s9Parchment20PagingViewControllerC7optionsAcA0B7OptionsV_tcfCTq
  Referenced from: /private/var/containers/Bundle/Application/EB8AE2C9-C6D2-4ECD-977F-2EE7F8D1509A/FistBumpSocial.app/FistBumpSocial
  Expected in: /private/var/containers/Bundle/Application/EB8AE2C9-C6D2-4ECD-977F-2EE7F8D1509A/com.app/Frameworks/Parchment.framework/Parchment
 in /private/var/containers/Bundle/Application/EB8AE2C9-C6D2-4ECD-977F-2EE7F8D1509A/com.app/app

any suggestions?

**Comment by rechsteiner** [comment] 2020-04-22 18:36
Hi @YanwuX! I just tried setting up a fresh CocoaPods project with target platform to iOS 12 using Xcode 11.4 and it works just fine for me. Could it be related to something like [this](https://stackoverflow.com/a/42349549)? Any other details you could share about your setup that might be relevant?

**Comment by rechsteiner** [comment] 2020-05-27 15:00
@YanwuX did you manage to get this working?

**Comment by rechsteiner** [comment] 2020-06-01 11:03
Closing this for now as I'm not able to reproduce. Please let me know if anyone still is having issues with this.

**Closed by rechsteiner** 2020-06-01 11:03 UTC
