### ISSUE TITLE
When clicking the left-side menu item, the page scrolls in the wrong direction

### ISSUE THREAD

**Issue by Liya86** [rechsteiner/Parchment#550] opened 2021-01-04 06:27 UTC
When clicking the left-side menu item, the page scrolls in the wrong direction（from right to left）

**Comment by rechsteiner** [comment] 2021-02-01 19:32
Hi @Liya86! Could you share a bit more about your setup? Are you using a custom `PagingItem`?

**Comment by yutoyazaki** [comment] 2021-03-14 15:01
I found the same behavior and was able to reproduce it with the Example.app.

1. Go to "Size delegate" page in the Example app
2. Swipe the menu all the way to the right and tap "Sydney"
3. Swipe back to the left and tap "Tokyo"

The paging animation should be reversed but it's going to forward.
I think this is something related to the `visibleItems` caches. When you select the left side of the current paging item, the paging animation will not work correct if the selected item is not contained in the `visibleItems` array.

**Comment by ZaVyLoN** [comment] 2021-04-07 14:40
Hi @rechsteiner. Is there a solution to this problem?

**Comment by rechsteiner** [comment] 2021-04-07 15:23
The problem seems to be related to the direction calculation here: https://github.com/rechsteiner/Parchment/blob/master/Parchment/Structs/PagingItems.swift#L53. Removing the first check there fixes the issue, but I can't remember why that was added in the first place. Trying to verify whether removing it will break something else before I push the fix.

**Comment by rechsteiner** [comment] 2021-04-07 15:43
Pushed a fix to the `fix-page-animation` branch, so you can target that until this has been released

**Comment by rechsteiner** [comment] 2021-10-16 13:06
This is now released in the `v3.1.0` version 🙂

**Closed by rechsteiner** 2021-10-16 13:06 UTC

**Comment by ZaVyLoN** [comment] 2021-11-10 14:02
@rechsteiner the problem is not solved yet. 
Conditions:
Add a PagingItem to the end of the array.

`let items: [PagingItem] = [
        PagingIndexItem(index: 1, title: "TODO"),
        PagingIndexItem(index: 2, title: "In Progress"),
        PagingIndexItem(index: 3, title: "Archive"),
        PagingIndexItem(index: 4, title: "Other"),
        IconItem(icon: "earth", index: 0) // in example this is first line
    ]`
    
Result:
Swipe - ok
Tap at item: bug
[](url)
https://imgur.com/a/jmkjZ97

**Comment by ZaVyLoN** [comment] 2021-11-11 17:23
dd a PagingItem to the end of the array.

`let items: [PagingItem] = [
        PagingIndexItem(index: 1, title: "TODO"),
        PagingIndexItem(index: 2, title: "In Progress"),
        PagingIndexItem(index: 3, title: "Archive"),
        PagingIndexItem(index: 4, title: "Other"),
        IconItem(icon: "earth", index: 0) // in example this is first line
    ]`
    
Result:
Swipe - ok
Tap at item: bug when tap icon tab (https://imgur.com/a/eZcs5i4)
