### ISSUE TITLE
Paging items do not get resized properly after reloading data

### ISSUE THREAD

**Issue by rptoma** [rechsteiner/Parchment#429] opened 2020-02-26 10:32 UTC
Consider the following scenario:

1. The paging view controller gets loaded with some data.
2. The data changes (including the number of pages/paging items) .
3. So, we call reloadData on the paging view controller.

Everything gets reloaded, the number of paging items get updated but they are not sized correctly. My guess is that the function that specifies widthForPagingItem does not get recalled after reload.

The only solution is to completely remove and re-add the view controller which is not ok at all.

Thank you.

**Comment by rechsteiner** [comment] 2020-03-04 20:31
Thanks for the report. I'll look into getting this fixed 🙂

**Comment by rechsteiner** [comment] 2020-03-05 21:32
Which version of Parchment are you using? I just tried reproducing this using one of the example targets, but it seems to work just fine. Here's the code I'm running (you can trigger a memory warning in the simulator to toggle the states):

```Swift
class ViewController: UIViewController {
  var expanded: Bool = false
  let pagingViewController = PagingViewController(viewControllers: [
    IndexViewController(index: 0),
    IndexViewController(index: 1)
  ])
  
  override func viewDidLoad() {
    super.viewDidLoad()
    pagingViewController.sizeDelegate = self
    addChild(pagingViewController)
    view.addSubview(pagingViewController.view)
    view.constrainToEdges(pagingViewController.view)
    pagingViewController.didMove(toParent: self)
  }
  
  override func didReceiveMemoryWarning() {
    expanded.toggle()
    pagingViewController.reloadData()
  }
}

extension ViewController: PagingViewControllerSizeDelegate {
  func pagingViewController(_: PagingViewController, widthForPagingItem pagingItem: PagingItem, isSelected: Bool) -> CGFloat {
    return expanded ? 200 : 100
  }
}
```

Do you see anything I'm missing for reproducing this?

**Comment by rptoma** [comment] 2020-03-06 07:14
Hey,

Thanks for checking it out.

The currently used version is  2.0.1, but it happened before, too (on 1.7.0).

The differences between what we do and your example are that:
1. We are using PagingViewControllerDataSource for setting the view controllers
2. We are using custom cells for the menu items

Thanks!

**Comment by rechsteiner** [comment] 2020-03-06 20:15
Tried setting up a data source and using custom cells, but it's still not able to reproduce this. Here's the current code I'm running:

```Swift
class ViewController: UIViewController {
  var expanded: Bool = false
  let pagingViewController = PagingViewController()
  
  class Cell: PagingCell {
    override func setPagingItem(_ pagingItem: PagingItem, selected: Bool, options: PagingOptions) {
      contentView.backgroundColor = .green
    }
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    pagingViewController.dataSource = self
    pagingViewController.sizeDelegate = self
    pagingViewController.register(Cell.self, for: PagingIndexItem.self)
    pagingViewController.menuItemSpacing = 5
    
    addChild(pagingViewController)
    view.addSubview(pagingViewController.view)
    view.constrainToEdges(pagingViewController.view)
    pagingViewController.didMove(toParent: self)
  }
  
  override func didReceiveMemoryWarning() {
    expanded.toggle()
    pagingViewController.reloadData()
  }
}

extension ViewController: PagingViewControllerDataSource {
  
  func pagingViewController(_: PagingViewController, pagingItemAt index: Int) -> PagingItem {
    return PagingIndexItem(index: index, title: "View \(index)")
  }
  
  func pagingViewController(_: PagingViewController, viewControllerAt index: Int) -> UIViewController {
    return IndexViewController(index: index)
  }
  
  func numberOfViewControllers(in pagingViewController: PagingViewController) -> Int {
    return 3
  }
  
}

extension ViewController: PagingViewControllerSizeDelegate {
  func pagingViewController(_: PagingViewController, widthForPagingItem pagingItem: PagingItem, isSelected: Bool) -> CGFloat {
    return expanded ? 200 : 100
  }
}
```

Any other ideas what might be different from your app?

**Comment by grifas** [comment] 2020-03-10 10:59
Same issue for me but apparently it's an other library causes the bug (`pod SkeletonView`).

**Comment by rptoma** [comment] 2020-03-10 11:04
@rechsteiner Not really. Something weird that I remember I noticed was that the first cells looked OK, but after scrolling a little bit, they were starting to have the wrong dimensions (i.e. too small to fit the content).

@grifas We don't use SkeletonView and it doesn't seem to be a dependency of Parchment. 🤔

**Comment by grifas** [comment] 2020-03-10 11:13
@rptoma Yeah I know but a line of this library causes the issue for my project. I didn't dig more into that but I just comment the line and I saw no more issue. I just thought maybe you are in the same case as me.

**Comment by rechsteiner** [comment] 2020-03-10 20:47
Hmm, okay. Could you share some examples of how you are calculating the width using the size delegate? Also, are you using a custom `PagingItem` as your data source?

**Comment by rechsteiner** [comment] 2020-03-10 21:19
I've made some changes to the way we're invalidating the size cache now (#444). Could you try to target the `master` branch and see if this fixes the issue you're facing?

**Comment by rptoma** [comment] 2020-03-11 10:16
It is solved now! Awesome, thanks! Looking forward to the new release.

**Comment by rechsteiner** [comment] 2020-03-11 21:01
Awesome! Thanks for helping me debug. The fix was just released in the latest version now: https://github.com/rechsteiner/Parchment/releases/tag/v2.1.0

**Closed by rechsteiner** 2020-03-11 21:01 UTC
