### ISSUE TITLE
如果能支持 自定义swith就好了

### ISSUE THREAD

**Issue by LZRight123** [rechsteiner/Parchment#510] opened 2020-08-04 06:42 UTC
如果能支持 自定义swith就好了

**Comment by rechsteiner** [comment] 2020-08-06 09:19
Hey @LZRight123! Could you explain in English what the issue is? I tried translating it, but I don't really understand

**Comment by Flybor** [comment] 2020-08-31 07:27
maybe you can use the protocol of PagingViewControllerSizeDelegate

**Comment by rechsteiner** [comment] 2020-09-02 19:10
@LZRight123 closing this for now, but let me know if you're still having some issues

**Closed by rechsteiner** 2020-09-02 19:10 UTC
