### ISSUE TITLE
Select(index: {number}) initial load problem

### ISSUE THREAD

**Issue by yakupad** [rechsteiner/Parchment#478] opened 2020-04-16 13:25 UTC
Hello,

When I call the 'select' function after the new update, I can't touch the other menu buttons for initial load. After scrolling the pages, I can touch the menu buttons. I am waiting for your suggestions for the solution of this problem. Otherwise I will have to go back to the old version.

**Comment by rocxteady** [comment] 2020-04-18 01:03
You should share your code so we can see what you did and try to make the same situation again on our side.

**Comment by rechsteiner** [comment] 2020-04-25 14:07
I'm not able to reproduce this. When are you calling select? Which version of Parchment are you using?

**Comment by rechsteiner** [comment] 2020-05-27 15:01
@yakupad any updates on this?

**Comment by rechsteiner** [comment] 2020-06-01 11:04
Closing this as I'm not able to reproduce. Let me know if you're still having issues with this 🙂

**Closed by rechsteiner** 2020-06-01 11:04 UTC
