### ISSUE TITLE
Attempt to scroll to invalid index path Crash [iPad related]

### ISSUE THREAD

**Issue by MarcosSorribas** [rechsteiner/Parchment#360] opened 2019-07-21 16:36 UTC
Hi all!

I've just released and **iPhone** app with a Parchment based pagination controller. Some users are using the app in iPad in the iPhone compatibility mode and the app starts crashing for them. I'm not able to reproduce the issue but I know that _**It only happens in iPad devices running my iOS app in compatibility mode.**_ 

This is the crash trace:

<img width="1338" alt="Screenshot 2019-07-21 at 18 37 57" src="https://user-images.githubusercontent.com/6518337/61593980-b8a29000-abe6-11e9-8207-f5847237cfcc.png">

<img width="922" alt="Screenshot 2019-07-21 at 18 33 38" src="https://user-images.githubusercontent.com/6518337/61593944-682b3280-abe6-11e9-9b36-4222d5c2d032.png">

Hope you can help me 🥺This bug is annoying me an some of my users.

**Comment by rechsteiner** [comment] 2019-09-01 11:03
Hi @MarcosSorribas! Thanks for the detailed report. I will try to find a fix for this. Let me know if you figure out a way to reproduce this

**Comment by rechsteiner** [comment] 2020-03-20 20:16
@MarcosSorribas are you still seeing this crash? If so, could you share a bit about your implementation? I'm not able to reproduce this using the Example project in compatibility mode

**Comment by MarcosSorribas** [comment] 2020-03-25 16:34
Hi, @rechsteiner I tried to fix it but I was unable to reproduce either. In the end, I removed Parchment from my codebase and use my own solution as a replacement. Sorry.

**Comment by rechsteiner** [comment] 2020-03-25 16:36
No worries, thanks for the update! I’ll just close this one then as I haven’t heard anyone else experiencing this

**Closed** 2020-03-25 16:36 UTC
