### ISSUE TITLE
Scrolling bug in the pagingViewController (IconsExample) when applying different width for selected cell in IconsExample

### ISSUE THREAD

**Issue by IVANKRUPSKI** [rechsteiner/Parchment#87] opened 2017-11-27 12:39 UTC
Hey,

I have tried to set up different width for selected cell in IconsExample, wIth selected 60pt and not selected 80pt.

When I slide from controller to controller, relatively fast, pagingViewController on the top occasionally jumps from icon to icon without scrolling animation.

I have added 

this 
```
extension ViewController: PagingViewControllerDelegate {
    
    func pagingViewController<T>(_ pagingViewController: PagingViewController<T>, widthForPagingItem pagingItem: T, isSelected: Bool) -> CGFloat {
        
        if isSelected {
            return 80
        } else {
            return 40
        }
    }
    
}
```

and this

```
  override func viewDidLoad() {
    ...
    pagingViewController.delegate = self
  }
```

 to the IconsExample ViewController. Did I miss anything? Was that correct?

**Comment by rechsteiner** [comment] 2017-12-11 16:56
Yeah, that's correct. I get same bug here as well. Not sure what could be causing that, but I'll try to get that fixed pretty soon 👍

**Comment by rechsteiner** [comment] 2017-12-25 14:50
I suspect this might have something to do with a bug I just fixed in #96, but I'm not 100% sure. At least I'm not able to reproduce the jumping after that fix. Could try out the latest master branch and see if you're still seeing this?

**Comment by IVANKRUPSKI** [comment] 2017-12-27 09:28
Unfortunately, bug is still there. I have 12 icons each 40 points in width, selected icon is 60 points in width.
I scroll the content controller one by one and selected paging menu item changes one by one, and when it reaches the middle, menu should scroll itself a bit, but it's slightly delayed and here is the flicker.

**Comment by IVANKRUPSKI** [comment] 2017-12-27 11:25
But you are right, there is no longer bug in your IconExample.
I will investigate why it is still there in our project.

**Comment by IVANKRUPSKI** [comment] 2017-12-27 13:24
Ok, I have noticed that it has definitely become better, however this flickering behavior is still there.
And the heavier the content controllers the buggier the behavior.

In your IconExample content controllers are empty, so you will hardly see any flicker.

In our case we have 12 collectionViews with hundreds of cells in each, so this does have an impact. 
I reduced the number of cells to one per each collectionView and noticed that the bug almost disappeared.

**Comment by IVANKRUPSKI** [comment] 2017-12-27 17:28
And in order to see this bug one should scroll controllers rather fast one by one.

**Comment by rechsteiner** [comment] 2018-01-05 16:23
Managed to figure out what was causing this; seems to be a performance issue with the way I was updating the content offset when the user is scrolling. Should be fixed it #106 ✌️ 

Let me know if this fixes your issue!

**Comment by IVANKRUPSKI** [comment] 2018-01-10 16:34
Yes, now it works smoothly. Thanks!

**Comment by rechsteiner** [comment] 2018-01-10 17:18
Awesome 👍

**Closed by rechsteiner** 2018-01-10 17:18 UTC
