### ISSUE TITLE
Crash when using SwiftPM

### ISSUE THREAD

**Issue by ymkim50** [rechsteiner/Parchment#398] opened 2019-11-13 15:07 UTC
I recently experienced a crash.

I installed it using SwiftPM but it crashed. It's release build, not debug build.
Here's the crashing part:

```
func createLayout <T> (layout: T.Type, options: PagingOptions)-> T where T: PagingLayout {
   return layout.init (options: options)
}
```

To test this, I ran a manual / Cocoapods installation. But there was no problem.
So I reinstalled with Cocoapods.

Some other libraries(e.g. SwiftyUserDefaults)  had same issue. Using generic seems to be the problem.

**Comment by pcmanik** [comment] 2019-11-15 20:37
Experiencing the same problem. It looks like the problem is in SPM itself

**Comment by ymkim50** [comment] 2019-11-16 07:39
You are right. From my testing, I'm having trouble with libraries that create instances using Generics in SwiftPM. As XCode is updated, the libraries generated by SwiftPM seem to be a problem. I had to move all the libraries back to Cocoapods.

**Comment by EdgarDegas** [comment] 2019-11-17 17:13
Experiencing this *Crash on Release Build* too, **also** when using another library named Moya. I’ve found no way but to switch back to Cocoapods.

**Comment by ymkim50** [comment] 2019-11-21 07:18
Please refer to the following link:
https://bugs.swift.org/browse/SR-11564?focusedCommentId=51285&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-51285

**Comment by rechsteiner** [comment] 2019-11-26 11:14
Thanks @ymkim50! Closing this issue as it’s not really much we can do about it.

**Closed by rechsteiner** 2019-11-26 11:14 UTC
