### ISSUE TITLE
UIScreenEdgePanGesture has no effect with Parchment

### ISSUE THREAD

**Issue by qiaqiaxian** [rechsteiner/Parchment#148] opened 2018-03-21 10:42 UTC
hello,
my child viewcontrolle are tableviews
but UIScreenEdgePanGesture has no effect
how to solve the issue?
thank you

**Comment by rechsteiner** [comment] 2018-03-23 09:52
Hello! You can require the page view controller gesture recognizer to fail when the `UIScreenEdgePanGestureRecognizer` is trigged like this:

```Swift
let recognizer = UIScreenEdgePanGestureRecognizer(target: self, action: #selector(handlePan))
pagingViewController.pageViewController.scrollView.panGestureRecognizer.require(toFail: recognizer)
```

Another options is to allow both recognizers to be triggered simultaneously:

```Swift
let recognizer = UIScreenEdgePanGestureRecognizer(target: self, action: #selector(handlePan))
recognizer.delegate = self

...

extension ViewController: UIGestureRecognizerDelegate {
  func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
  }
}
```

Does that work for you?

**Comment by qiaqiaxian** [comment] 2018-03-23 10:57
Thanks for your reply.
Neither of them does not work.
Actually, i use 'handleNavigationTransition' in my custom NavigationController.
So, it's a FullScreen pop.

**Comment by rechsteiner** [comment] 2018-03-23 11:15
Ah okay. Does it work to require it to fail on the `interactivePopGestureRecognizer` property? E.g. something like this:

```Swift
pagingViewController.pageViewController.scrollView.panGestureRecognizer.require(toFail: interactivePopGestureRecognizer)
```

**Comment by qiaqiaxian** [comment] 2018-03-23 11:25
> pagingViewController.pageViewController.scrollView.panGestureRecognizer.require(toFail: interactivePopGestureRecognizer)
i tried this before, it didn't work.

**Comment by rechsteiner** [comment] 2018-03-23 11:49
Does the interactive pop recognizer work when using it without the PagingViewController? Just tried it locally with a default navigation controller and it seems to work just fine.

**Comment by qiaqiaxian** [comment] 2018-03-23 11:59
Yes.it works with other viewcontrollers.
i tried to use default navigation controller a moment ago.
and didn't work ... 
i am sorry

**Comment by rechsteiner** [comment] 2018-03-25 17:30
Hmm, not sure why that isn't working. Seems to be working just fine here. Could you provide some more details on your implementation?

**Comment by rechsteiner** [comment] 2018-05-01 12:58
@qiaqiaxian I can't find any issues with this when I'm testing locally. I'm closing this for now, but feel free to reopen if you find any ways of reproducing this 👍

**Closed by rechsteiner** 2018-05-01 12:58 UTC

**Comment by wwwdotfa** [comment] 2020-04-27 13:13
@rechsteiner I encountered a similar problem with @qiaqiaxian, u used horizontal scrollview to contain pages, so `scrollView.panGestureRecognizer.require(toFail: recognizer)` never failed. This seems to be a very common problem. I hook the problem temporarily using the following method:

```
extension UIScrollView: UIGestureRecognizerDelegate {
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer is UIPanGestureRecognizer {
            return true
        }
        return false
    }
}

extension EMPageViewController: UIGestureRecognizerDelegate {
    override open func viewDidLoad() {
        super.viewDidLoad()
        self.scrollView.delegate = self
        self.view.addSubview(self.scrollView)
        scrollView.panGestureRecognizer.delegate = scrollView
    }
}
```

I think it would be more elegant to use a custom view inherit ScrollView in EMPageViewController, because the delegate of panGestureRecognizer is only allowed to be scrollView self. 

Thanks.
