### ISSUE TITLE
Parchment header issues when change index

### ISSUE THREAD

**Issue by chrisk810** [rechsteiner/Parchment#364] opened 2019-08-13 08:28 UTC
There is a glitch on the content offset of the header view when switch to another index, this also happens on your Header Example.

**Comment by rechsteiner** [comment] 2019-09-01 11:08
Yeah, this is a duplicate of #338. As I mentioned there, those examples are just to illustrate what you can do with Parchment. I will try to fix that specific example, but it's really up to your app to determine how you want this to work.

**Closed by rechsteiner** 2019-09-01 11:08 UTC
