### ISSUE TITLE
The package product 'Parchment' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by Wei18** [rechsteiner/Parchment#659] opened 2023-03-06 03:26 UTC
As title, on version 3.2.0.

**Comment by rechsteiner** [comment] 2023-03-07 19:42
Duplicate of #634. Will look into getting this fixed soon!

**Closed by rechsteiner** 2023-03-07 19:42 UTC

**Comment by rechsteiner** [comment] 2023-03-07 20:53
Fixed in version 3.2.1!

**Comment by Wei18** [comment] 2023-03-08 02:01
Thanks.
